#   Curve

language: c

#   Build required projects first
before_script:

#   libsodium
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..

#   libzmq
- git clone git://github.com/zeromq/libzmq.git
- cd libzmq
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..

#   CZMQ
- git clone git://github.com/zeromq/czmq.git
- cd czmq
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..

#   Build and check libcurve
script: ./autogen.sh && ./configure && make && make check
